### ISSUE TITLE
Crashed when doing the unlocks after beating the heart

### ISSUE THREAD

**Issue by SilentJ28** [JohnnyDevo/The-Mystic-Project#10]
I beat the heart, then the progress bar filled one level, then got within 1 exp of filling the next level and the game crashed.

21:36:45.102 INFO screens.VictoryScreen> Clicked
21:36:51.941 ERROR core.CardCrawlGame> Exception caught
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
	at com.megacrit.cardcrawl.neow.NeowUnlockScreen.open(NeowUnlockScreen.java:56) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.screens.VictoryScreen.update(VictoryScreen.java:857) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2541) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:882) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:434) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

full log:
[SlayTheSpire.log](https://github.com/JohnnyDevo/The-Mystic-Project/files/2601663/SlayTheSpire.log)

**Comment by SilentJ28** [comment]
modlist:

![image](https://user-images.githubusercontent.com/40654703/48804704-61f55700-ece3-11e8-95a2-e438fe91fd28.png)

**Comment by SilentJ28** [comment]
This might be something more general with modded characters. Crashed in the same situation with Gatherer
