### ISSUE TITLE
Crash after act 3 (v. 0.5.7)

### ISSUE THREAD

**Issue by fkinghatesigningup** [JohnnyDevo/The-Mystic-Project#2]
Exception: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: title/title.png
07:18:46.581 ERROR core.CardCrawlGame> Exception caught
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: title/title.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.load(TextureAtlas.java:244) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:236) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:231) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:226) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.g2d.TextureAtlas.<init>(TextureAtlas.java:216) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.scenes.TitleBackground.<init>(TitleBackground.java:49) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.<init>(MainMenuScreen.java:70) ~[?:?]
	at com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.<init>(MainMenuScreen.java:107) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.updateFade(CardCrawlGame.java:623) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:760) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:464) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Caused by: java.io.IOException: Error loading pixmap: decoder init failed for stream
	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<init>(Gdx2DPixmap.java:90) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:146) ~[desktop-1.0.jar:?]
	... 15 more
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by NellyDevo** [comment]
Could you possibly provide more information? Such as what other mods were you running, if any.

EDIT: It also might be relevant, so could you provide your system specs if possible?

**Comment by fkinghatesigningup** [comment]
I was just using the BaseMod v3.0.2 , if you let me know how to get my system specs i'll give them to you (windows pc).

**Comment by NellyDevo** [comment]
if you're using windows 10, you can right click the start button, select Run, and open msinfo32.exe for the information.

Most relevant is probably how much RAM you have, as that error is most often a result of low RAM or a memory leak, when the file actually exists.

**Comment by fkinghatesigningup** [comment]
Installed Physical Memory (RAM)	8.00 GB
Total Physical Memory	7.91 GB
Available Physical Memory	4.48 GB
I played the new patch today, cantrip felt balanced.
